### ISSUE TITLE
Change num_articles to be responsive, rather than fixed input parameter [3h]

### ISSUE THREAD

**Issue by phufbv** [phufbv/journal-stats#31]
Currently hard-coding sample size, e.g. 10 articles per volume. Some volumes (esp. Letters) have fewer than 10 articles though - results in array overflow:
Traceback (most recent call last):
  File "script.py", line 54, in <module>
    run(parameters.journal.upper(), parameters.num_articles)
  File "script.py", line 37, in run
    url = articles[num]
IndexError: list index out of range

Need to:
- Detect number of articles in the volume being sampled
- Set num_articles to be min of this or hard-coded value
- Update readme

**Comment by phufbv** [comment]
Can also reproduce by running publication-dates_07-02-20 script.py with parameters:

# Select journal - must be either "ApJ" or "ApJL"
journal = "ApJ"

# Number of articles to use from each issue
num_articles = 30

Errors out after 18th article.
